ci: Ensure that SHAs aren't empty

diff --git a/.github/workflows/flutter-channel.yaml b/.github/workflows/flutter-channel.yaml
--- a/.github/workflows/flutter-channel.yaml
+++ b/.github/workflows/flutter-channel.yaml
@@ -28,6 +28,10 @@ jobs:
               https://api.github.com/repos/flutter/flutter/branches/${{ matrix.channel }} |
             jq -r '.commit.sha'
           )
+          if [ -z "$sha" ] || [ "$sha" == "null" ]; then
+            echo "Error: Could not retrieve SHA for ${{ matrix.channel }}"
+            exit 1
+          fi
           echo "$sha" >flutter_ref-${{ matrix.channel }}
         working-directory: ./actions/setup-flutter-and-dart/
 
diff --git a/actions/setup-flutter-and-dart/action.yaml b/actions/setup-flutter-and-dart/action.yaml
--- a/actions/setup-flutter-and-dart/action.yaml
+++ b/actions/setup-flutter-and-dart/action.yaml
@@ -22,6 +22,10 @@ runs:
         sha=$(
         cat flutter_ref-${{ inputs.flutter-channel }}
         )
+        if [ -z "$sha" ] || [ "$sha" == "null" ]; then
+          echo "Error: Empty or null SHA found in flutter_ref-${{ inputs.flutter-channel }}"
+          exit 1
+        fi
         echo "sha=$sha" >> "$GITHUB_OUTPUT"
       working-directory: ./actions/setup-flutter-and-dart/
 
